package(default_visibility = ["//src:__subpackages__"])

# For generating skydoc
exports_files(glob(["*.bzl"]))

#npm_package(
#    name = "npm",
#    srcs = [
#        "//:package.json",
#    ],
#    tags = [
#        "release",
#    ],
#    deps = [
#        ":svelte-compiler-wrapped",
#    ],
#)
